### ISSUE TITLE
Explain why do we need a tools package

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-service#102]
https://github.com/open-telemetry/opentelemetry-service/tree/master/tools

Can this be removed?

**Comment by tigrannajaryan** [comment]
@owais can you shine on this? I don't remember what for was this exactly.

**Comment by bogdandrutu** [comment]
Also if this is internal consider to move it under the internal directory.

**Comment by owais** [comment]
It was added so we could pin tool dependencies to go.mod and have better guarantees about everyone using the same version of the tools. It doesn't have to be a separate package and can be moved to root. 

More on it here: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

**Comment by bogdandrutu** [comment]
Probably can be in the internal directory. Trying to avoid having too many packages/files in the root if not necessary.

**Comment by owais** [comment]
Makes sense. Will move to internal.

**Comment by bogdandrutu** [comment]
Also please add a comment in the file why is it needed. That ensures others will not get confused like me.

**Comment by owais** [comment]
Will add the comment. Do you think keeping it in internal (as opposed to root) might incorrectly suggest that the tools are only required by the internal package?

**Comment by bogdandrutu** [comment]
I don't, I think we have no intention to export public anything from this file so it should not be in the root.
