### ISSUE TITLE
test: TestCreateReceiver failed on Darwin

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#104]
Just received this one locally, notice that I'm on Darwin

```terminal
--- FAIL: TestCreateReceiver (0.00s)
    factory_test.go:43: 
                Error Trace:    factory_test.go:43
                Error:          Expected nil, but got: &errors.errorString{s:"failed to create new VMMetricsCollector: could not read /proc: stat /proc: no such file or directory"}
                Test:           TestCreateReceiver
    factory_test.go:44: 
                Error Trace:    factory_test.go:44
                Error:          Expected value not to be nil.
                Test:           TestCreateReceiver
```

**Comment by tigrannajaryan** [comment]
Hmm, the test probably needs to be skipped on Darwin? I am not sure if vmmetrics is expected/supposed to work on Darwin?

**Comment by songy23** [comment]
Currently VM Metrics receiver only supports Linux. For Darwin, Windows etc. the config should just exit without errors.

**Comment by songy23** [comment]
See https://github.com/census-instrumentation/opencensus-service/blob/c07166e49481bf0ba6dbb9a146fd6c21d0344d95/receiver/vmmetricsreceiver/metrics_receiver.go#L85-L95.

**Comment by tigrannajaryan** [comment]
Thanks @songy23 
@pjanotti Can you add the "skip" and test on your machine? I don't have a Mac to test.
