### ISSUE TITLE
Remove "Data" suffix from consumerdata.TraceData and consumerdata.MetricsData

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#118]
Instead of consumerdata.TraceData and consumerdata.MetricsData, simply consumerdata.Trace and consumerdata.Metrics

**Comment by bogdandrutu** [comment]
I think we use the suffix in a lot more places, if you really want to be consistent we need to remove TraceConsumer, TraceReceiver, TraceExporter, etc.

**Comment by pjanotti** [comment]
I'm starting to sour on this idea: "trace" can be interpreted as the trace of a single operation and "TraceData" captures better the idea that its a bundle of data related to traces. It also involves a large rename of parameters and locals.

**Comment by pjanotti** [comment]
If we want to proceed with this we will have to use something like `consumerdata.SpanBatch` ...

**Comment by pjanotti** [comment]
Completed soured in my mind...
