### ISSUE TITLE
Identify receivers, exporters and processors that will be part of the core.

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-service#13]
Core OpenTelemetry Service will include only a subset of receivers and exporters that are currently supported by OpenCensus Service.

The rest of receivers and exporters will be moved to a separate contrib repo.

Here is the proposed list of receivers and exporters that will be supported by OpenTelemetry Service code:

- Prometheus
- Jaeger (agent and collector ones)
- Zipkin
- OpenCensus, temporarily until OpenTelemetry one is available (we may want to keep OC for longer to facilitate migrations)

**Comment by tigrannajaryan** [comment]
@pjanotti @bogdandrutu please comment.

**Comment by pjanotti** [comment]
I agree with this set.

**Comment by tigrannajaryan** [comment]
Done, added as a doc.
