### ISSUE TITLE
contrib: setup proper repo for contrib

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#140]
We need to create define the structure and create the repo for contrib to separate respective code, issues, and PRs.

**Comment by pjanotti** [comment]
Some issues to migrate:
#125 
#124 
#122

**Comment by tigrannajaryan** [comment]
Repo added https://github.com/open-telemetry/opentelemetry-service-contrib/

**Comment by pjanotti** [comment]
Issues transferred.
