### ISSUE TITLE
all: Enforce check on license header.

### ISSUE THREAD

**Issue by songy23** [open-telemetry/opentelemetry-service#153]
For example https://github.com/open-telemetry/opentelemetry-service/blob/6566e78b4bb8e0cceec21abec91731611e3ca31a/internal/collector/telemetry/process_telemetry.go doesn't have a license header.

**Comment by MohamedElqdusy** [comment]
- Do you have a specific tool to check it in Go? 
- I found [addlicense](https://github.com/google/addlicense)

**Comment by songy23** [comment]
@MohamedElqdusy This tool looks promising - do you mind adding the check to this repo? If you don't have time I can take a look too.

**Comment by MohamedElqdusy** [comment]
Ok, I will give it a try at the weekend.

**Comment by songy23** [comment]
Fixed in #185.
