### ISSUE TITLE
exporter: jaeger thrift-tchannel deprecation

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-service#227]
OTelSvc will provide Jaeger exporters for gRPC and thrift-http - thrift-tchannel is considered legacy by Jaeger and is being replaced by gRPC. As we are releasing a new service there seems to be no reason for us to include such legacy.

If there is demand for thrift-tchannel we should implement it on the contrib repo for OTelSvc.

/cc @yurishkuro @jpkrohling

**Comment by yurishkuro** [comment]
+1, tchannel implementation doesn't play nicely with DNS load balancers, AND is deprecated.
