### ISSUE TITLE
vsock support in library and agent, and support for multiple inputs in agent

### ISSUE THREAD

**Issue by egernst** [open-telemetry/opentelemetry-service#241]
Very happy to see the very active work on this project!

I am eager to adopt opencensus/open-telemetry for the Kata Containers project, but we have a couple of particular needs that I'd like to see if we can add support for.

In our configuration, we have an application

**Comment by songy23** [comment]
Seems duplicated of https://github.com/open-telemetry/opentelemetry-service/issues/242.

**Comment by egernst** [comment]
My fault.  Inadvertent test to see if anyone would read the issue.  Test passed!
