### ISSUE TITLE
Setup Travis CI builds

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-service#26]

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev I don't seem to have rights to configure the repo to be able to add the Travis CI build.
Since I am a maintaner can you give the rights to be able to change repo settings so that I can configure branch protection rules, etc?

**Comment by bogdandrutu** [comment]
Done, also removed @flands since he is not a maintainer, you and @pjanotti can help him if anything is needed.

**Comment by tigrannajaryan** [comment]
Thanks.
