### ISSUE TITLE
Deteremine placement for Fan Out Processor

### ISSUE THREAD

**Issue by ccaraman** [open-telemetry/opentelemetry-service#283]
https://github.com/open-telemetry/opentelemetry-service/tree/master/processor/fanoutprocessor
isn't a true processor. It isn't configurable by users.
Should this be under processors or an internal component?

This issue is track determining where it should go and updating any relevant documentation for it.

**Comment by tigrannajaryan** [comment]
`fanoutprocessor` is briefly mentioned in the design.md.

I think we need to remove references to it from readme.md (the idea being that readme.md is intended for end users and design.md is intended for contributors). In addition I think we need to rename fanoutprocessor to something else, particularly get rid of `processor` suffix to avoid confusion with pipeline processors.

**Comment by pjanotti** [comment]
Some suggestions `fanoutconnector` or `fanoutadapter` ...

**Comment by tigrannajaryan** [comment]
I like `fanoutconnector`, I will fix this.

**Comment by pjanotti** [comment]
Closed via #285
