### ISSUE TITLE
Add factory and new-style config for Jaeger exporter

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-service#36]
See OpenCensus exporter factory.go and config.go as an example.

**Comment by MohamedElqdusy** [comment]
Hi @tigrannajaryan, I'd like to pick this one.

**Comment by tigrannajaryan** [comment]
@MohamedElqdusy great! Assigned to you.

**Comment by pjanotti** [comment]
Sorry I missed this one: we need to do this via simple senders, that don't have their own queue and consistently handle service name. The exporter should not be based on the client library one.
