### ISSUE TITLE
cmd/occollectpr/Dockerfile and cmd/otelsvc/Dockerfile assumes platform is always linux

### ISSUE THREAD

**Issue by etsangsplk** [open-telemetry/opentelemetry-service#49]
both of those files assumes the built platform is always linus but in Makefile unde rthe main repo, it tries to detect it on runtime. So this will fail on say darwin.

Example:
FROM alpine:latest as certs
RUN apk --update add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY occollector_linux / .  <---
ENTRYPOINT ["/occollector_linux"] <<-----
EXPOSE 55678

**Comment by pjanotti** [comment]
Hi @etsangsplk the docker images are built always for linux since it runs on top scratch images. See https://github.com/open-telemetry/opentelemetry-service/blob/master/Makefile#L92-L94

**Comment by etsangsplk** [comment]
My repo is old.
