### ISSUE TITLE
Fix Preceiver creation in prometheusreceiver/factory.go to pass the logger

### ISSUE THREAD

**Issue by tigrannajaryan** [open-telemetry/opentelemetry-service#66]
Change in https://github.com/open-telemetry/opentelemetry-service/pull/65 did not implement this.

Preceiver creation in prometheusreceiver/factory.go to pass the logger. That in turn will require CreateMetricsReceiver() to accept the logger as a parameter.

**Comment by tigrannajaryan** [comment]
Also look into adding E2E test for Prometheus: https://github.com/open-telemetry/opentelemetry-service/issues/67

**Comment by dinooliva** [comment]
Understood - I'll put together a pr for it.

**Comment by dinooliva** [comment]
Looked into the issue - for clarification, factory.CreateMetricsReceiver(...) currently takes two standard parameters (i.e. cfg and consumer) - simply adding the parameter to my local CreateMetricReceiver doesn't compile (unsurprisingly) 

To add the logger, it looks like I need to update the CreateMetricReceiver signature in https://github.com/open-telemetry/opentelemetry-service/blob/master/internal/factories/factories.go and update all uses - is that correct?

**Comment by tigrannajaryan** [comment]
@dinooliva yes, that's correct. 

@owais you also needed exactly this. Any chance your already started working on this?

**Comment by tigrannajaryan** [comment]
For uniformity we also need to pass the logger to `CreateTraceReceiver`.

We already pass the logger in `CreateTraceProcessor`/`CreateMetricsProcessor` as the first parameter, so let's make it the first parameter everywhere.

We can also do the exact same thing for exporters, either in the same PR or as a separate PR.

**Comment by owais** [comment]
> @owais you also needed exactly this. Any chance your already started working on this?

No, not working on this specifically and would benefit from this greatly. Thanks.

**Comment by dinooliva** [comment]
Sounds good - I should be able to take care of it early next week.

**Comment by dinooliva** [comment]
Fixed. I've also created issue #75 for exporters - I'll try to fix that one later this week.
