### ISSUE TITLE
Rename models package to configmodels

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-service#99]
Models is not suggestive enough to represent the meaning of this package.

**Comment by tigrannajaryan** [comment]
I suggest to move `configmodels.go` to `config/models` package, `commonerrors.go` to `errors` package and eliminate `models` package.

**Comment by bogdandrutu** [comment]
I don't think we need an errors package see https://github.com/open-telemetry/opentelemetry-service/issues/107. I think it is good to just move models to config/configmodels - this way the package name matches the directory name.

**Comment by tigrannajaryan** [comment]
Sounds good regarding `config/configmodels`.

>I don't think we need an errors package see #107. 
We still need a place for `commonerrors.go` which currently contains `ErrDataTypeIsNotSupported`. This error is used by receivers and exporters, so unclear which package to place it if we don't have `errors` package.
